//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeSDetail
    {
        [Required(ErrorMessage = "Please Enter the Id")]
        public int id { get; set; }
        [Required(ErrorMessage = "Please Enter the UName")]
        public string User_Name { get; set; }
        [Required(ErrorMessage = "Please Enter the Pass")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please Enter the Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter the Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter the Mobile Number")] [StringLength(10)]
        public string Mobile_Number { get; set; }
        [Required(ErrorMessage = "Please Enter the Age")]
        [Range(20, 53, ErrorMessage = "Age should be between 20 to 53")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Please Enter the Salary")]
        [Range(10000, 1000000, ErrorMessage = "Salary should be between 10000 to 1000000")]
        public Nullable<int> Salary { get; set; }
        [Required(ErrorMessage = "Please Enter the Email")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please Enter the Correct Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter the Country")]
        public string Country { get; set; }
        
        [Required(ErrorMessage = "Please Enter Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyy}")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        
        [Required(ErrorMessage = "Please Enter Date of Joining")]
        [DataType(DataType.Date)]
        [DisplayFormat (DataFormatString = "{0:MM-dd-yyy}")]
       
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        [Required(ErrorMessage = "Please Enter the Department")][StringLength(20)]
        public string Department { get; set; }

        public class DOBDateValidation : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                DateTime date;
                bool parsed = DateTime.TryParse(value.ToString(), out date);
                if (!parsed)
                    return new ValidationResult("Invalid Date");
                else
                {
                    var min = DateTime.Now;
                    var msg = string.Format("Please check the date you have entered", min);
                    try
                    {
                        if (date >= min)
                            return new ValidationResult(msg);
                        else
                            return ValidationResult.Success;
                    }
                    catch (Exception e)
                    {
                        return new ValidationResult(e.Message);
                    }
                }
            }
        }
    }
}
